name: Build and Release Binaries

on:
  release:
    types: [created]

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux
            arch: x64
            binary_name: wsserver
            archive_name: wsserver-linux-x64.tar.gz
          - os: ubuntu-latest
            platform: linux
            arch: arm64
            binary_name: wsserver
            archive_name: wsserver-linux-arm64.tar.gz
          - os: macos-latest
            platform: darwin
            arch: x64
            binary_name: wsserver
            archive_name: wsserver-macos-x64.tar.gz
          - os: macos-latest
            platform: darwin
            arch: arm64
            binary_name: wsserver
            archive_name: wsserver-macos-arm64.tar.gz
          - os: windows-latest
            platform: windows
            arch: x64
            binary_name: wsserver.exe
            archive_name: wsserver-windows-x64.zip

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build binary
        run: |
          bun build src/main.ts --compile --target=bun-${{ matrix.platform }}-${{ matrix.arch }} --outfile ${{ matrix.binary_name }}

      - name: Create archive (Linux/macOS)
        if: matrix.platform != 'windows'
        run: |
          chmod +x ${{ matrix.binary_name }}
          tar -czf ${{ matrix.archive_name }} ${{ matrix.binary_name }}
          md5sum ${{ matrix.archive_name }} > ${{ matrix.archive_name }}.md5

      - name: Create archive (Windows)
        if: matrix.platform == 'windows'
        shell: pwsh
        run: |
          Compress-Archive -Path ${{ matrix.binary_name }} -DestinationPath ${{ matrix.archive_name }}
          $hash = Get-FileHash -Path ${{ matrix.archive_name }} -Algorithm MD5
          "$($hash.Hash.ToLower())  ${{ matrix.archive_name }}" | Out-File -Encoding ASCII ${{ matrix.archive_name }}.md5

      - name: Upload archive to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./${{ matrix.archive_name }}
          asset_name: ${{ matrix.archive_name }}
          asset_content_type: application/gzip

      - name: Upload MD5 checksum to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./${{ matrix.archive_name }}.md5
          asset_name: ${{ matrix.archive_name }}.md5
          asset_content_type: text/plain