name: Build and Release Binaries

on:
  release:
    types: [created]

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux
            arch: x64
            artifact_name: wsserver-linux-x64
          - os: ubuntu-latest
            platform: linux
            arch: arm64
            artifact_name: wsserver-linux-arm64
          - os: macos-latest
            platform: darwin
            arch: x64
            artifact_name: wsserver-macos-x64
          - os: macos-latest
            platform: darwin
            arch: arm64
            artifact_name: wsserver-macos-arm64
          - os: windows-latest
            platform: windows
            arch: x64
            artifact_name: wsserver-windows-x64.exe

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build binary
        run: |
          bun build src/main.ts --compile --target=bun-${{ matrix.platform }}-${{ matrix.arch }} --outfile ${{ matrix.artifact_name }}

      - name: Upload binary to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./${{ matrix.artifact_name }}
          asset_name: ${{ matrix.artifact_name }}
          asset_content_type: application/octet-stream
